import type { DealCandidate } from '../types.js';

// Fallback deal universe used when BRIGHTDATA_API_KEY is not set.
// Once a key is present, integrations/brightdata.ts scrapes live current
// offers instead and these are only used if that call fails.
export const SEED_DEALS: DealCandidate[] = [
  {
    id: 'csp-60k',
    institution: 'Chase',
    title: 'Chase Sapphire Preferred — 60,000 point sign-up bonus',
    category: 'travel-card',
    headlineValue: '60,000 points (~$750 in travel)',
    requirement: 'Spend $4,000 in the first 3 months',
    requirementDays: 90,
    sourceUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred',
    source: 'seed',
  },
  {
    id: 'amex-gold-60k',
    institution: 'American Express',
    title: 'Amex Gold Card — welcome offer',
    category: 'cashback-card',
    headlineValue: '60,000 Membership Rewards points',
    requirement: 'Spend $6,000 in the first 6 months',
    requirementDays: 180,
    sourceUrl: 'https://www.americanexpress.com/us/credit-cards/card/gold-card/',
    source: 'seed',
  },
  {
    id: 'lowes-store-card',
    institution: "Lowe's",
    title: "Lowe's Advantage Card — new cardholder discount",
    category: 'store-card',
    headlineValue: '20% off first purchase, up to $100',
    requirement: 'Open the card and make one purchase within 30 days',
    requirementDays: 30,
    sourceUrl: 'https://www.lowes.com/l/credit-cards',
    source: 'seed',
  },
  {
    id: 'alaska-companion',
    institution: 'Alaska Airlines',
    title: 'Alaska Airlines Visa — Companion Fare + bonus miles',
    category: 'airline',
    headlineValue: 'Companion fare from $99 + 60,000 miles',
    requirement: 'Spend $3,000 in the first 90 days',
    requirementDays: 90,
    sourceUrl: 'https://www.alaskaair.com/content/credit-cards',
    source: 'seed',
  },
  {
    id: 'citi-checking-300',
    institution: 'Citi',
    title: 'Citi Priority Checking — new account bonus',
    category: 'bank-bonus',
    headlineValue: '$300 cash bonus',
    requirement: 'Deposit $15,000 in new-to-Citi funds within 20 days, maintain 60 days',
    requirementDays: 60,
    sourceUrl: 'https://online.citi.com/US/JRS/pands/detail.do?ID=CitiPriorityChecking',
    source: 'seed',
  },
  {
    id: 'wells-fargo-100k',
    institution: 'Wells Fargo Premier',
    title: 'Wells Fargo Premier Checking — high-balance relationship bonus',
    category: 'bank-bonus',
    headlineValue: '$2,000 cash bonus',
    requirement: 'Open new account and maintain a $100,000+ combined balance for 90 days',
    requirementDays: 90,
    sourceUrl: 'https://www.wellsfargo.com/checking/premier/',
    source: 'seed',
  },
  {
    id: 'venture-x-75k',
    institution: 'Capital One',
    title: 'Venture X — sign-up bonus',
    category: 'travel-card',
    headlineValue: '75,000 miles (~$750 in travel)',
    requirement: 'Spend $4,000 in the first 3 months',
    requirementDays: 90,
    sourceUrl: 'https://www.capitalone.com/credit-cards/venture-x/',
    source: 'seed',
  },
  {
    id: 'schwab-checking-transfer',
    institution: 'Charles Schwab',
    title: 'Schwab Brokerage — asset transfer bonus',
    category: 'bank-bonus',
    headlineValue: 'Up to $1,000 cash bonus',
    requirement: 'Transfer $100,000+ in new assets within 45 days, hold 12 months',
    requirementDays: 45,
    sourceUrl: 'https://www.schwab.com/',
    source: 'seed',
  },
  {
    id: 'homedepot-consumer',
    institution: 'Home Depot',
    title: 'Home Depot Consumer Credit Card — special financing',
    category: 'store-card',
    headlineValue: '0% APR for 6 months on $299+ purchases',
    requirement: 'Open the card, purchase within 30 days',
    requirementDays: 30,
    sourceUrl: 'https://www.homedepot.com/c/credit_center',
    source: 'seed',
  },
  {
    id: 'united-explorer-70k',
    institution: 'United Airlines',
    title: 'United Explorer Card — bonus miles',
    category: 'airline',
    headlineValue: '70,000 bonus miles',
    requirement: 'Spend $5,000 in the first 3 months',
    requirementDays: 90,
    sourceUrl: 'https://creditcards.chase.com/travel-credit-cards/united',
    source: 'seed',
  },
  {
    id: 'chase-total-checking-300',
    institution: 'Chase',
    title: 'Chase Total Checking — new account bonus',
    category: 'bank-bonus',
    headlineValue: '$300 cash bonus',
    requirement: 'Open the account and set up direct deposits totaling $500+ within 90 days',
    requirementDays: 90,
    sourceUrl: 'https://www.chase.com/personal/checking/total-checking',
    source: 'seed',
  },
  {
    id: 'bofa-advantage-200',
    institution: 'Bank of America',
    title: 'Advantage Banking — new account bonus',
    category: 'bank-bonus',
    headlineValue: '$200 cash bonus',
    requirement: 'Open the account and make two qualifying direct deposits within 90 days',
    requirementDays: 90,
    sourceUrl: 'https://www.bankofamerica.com/deposits/bank-account-offers/',
    source: 'seed',
  },
  {
    id: 'pnc-virtual-wallet-200',
    institution: 'PNC',
    title: 'Virtual Wallet — new account bonus',
    category: 'bank-bonus',
    headlineValue: '$200 cash bonus',
    requirement: 'Open the account and receive $500+ in direct deposits each month for 2 straight months',
    requirementDays: 60,
    sourceUrl: 'https://www.pnc.com/en/personal-banking/banking/pnc-bank-checking-account-offers.html',
    source: 'seed',
  },
  {
    id: 'usbank-smartly-450',
    institution: 'U.S. Bank',
    title: 'Smartly Checking — tiered new account bonus',
    category: 'bank-bonus',
    headlineValue: 'Up to $450 cash bonus',
    requirement: 'Open the account and deposit $6,000+ in new-to-U.S.-Bank funds within 60 days',
    requirementDays: 60,
    sourceUrl: 'https://www.usbank.com/bank-accounts/checking-accounts/smartly-checking.html',
    source: 'seed',
  },
];
